### PR TITLE
Update tags transform to convert wof l10n names

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/mapzen/vector-datasource/issues/418

I did the fastest thing to convert to two letter language codes to match the osm convention, namely to just take the first two characters. I don't think this is right. Any thoughts as to how we should actually do the conversion? Specifically, we need to convert from 639-3 -> 639-1

@zerebubuth could you review please?

### CODE REVIEW

**Comment by zerebubuth** [comment]
Yup, it looks like `bos` for Bosnian should shorten to `bs`, as `bo` is already used for Tibetan.

The full list can be downloaded from [here](http://www-01.sil.org/iso639-3/download.asp), but has some unusual restrictions on redistribution.

We could try using the `to_iso639_1` function from [the ISO639 PyPI package](https://pypi.python.org/pypi/iso639/)?

**Comment by zerebubuth** [comment]
Update from meeting: [pycountry](https://bitbucket.org/flyingcircus/pycountry) looks better, as it has ISO 639-3 support as well.

**Comment by rmarianski** [comment]
Using pycountry to convert language codes in 9261437.

**Comment by nvkelso** [comment]
Can we add a test for San Francisco (which has a ton of language name variants), please?

**Comment by rmarianski** [comment]
> Can we add a test for San Francisco (which has a ton of language name variants), please?

The [wof neighbourhood](https://whosonfirst.mapzen.com/data/858/826/41/85882641.geojson) only has one variant, the Spanish one. And since it's the same value as the `name`, we don't include it.

I added a test for Hollywood in [07b5e5a](https://github.com/mapzen/vector-datasource/pull/816/commits/07b5e5a4403d43fbbd0baf579833de48520f4e98).

**Comment by zerebubuth** [comment]
:+1:

**Comment by rmarianski** [comment]
Updated transform to use iso-639-3 codes across osm and wof in 1297fba.

**Comment by nvkelso** [comment]
Nice! What does San Francisco (from OSM) look like now? Same for updated Hollywood test?

**Comment by nvkelso** [comment]
I see updated tests for OSM and WOF in https://github.com/mapzen/vector-datasource/commit/4848780a81ab6be87afa385ee0afe24b20c37809.

How would this handle `en_US` and other country variants? I think WOF supports that now (I could be dreaming).

**Comment by rmarianski** [comment]
> I see updated tests for OSM and WOF in mapzen/vector-datasource@4848780.

Yea, all features, including osm, now have 3 letter codes, ie `name:eng=foo`. This is a breaking change because previously osm features had 2 letter codes (really just passed through the source tags)

> How would this handle en_US and other country variants? I think WOF supports that now (I could be dreaming).

Do you have an example? Based on the docs I've read both [osm](http://wiki.openstreetmap.org/wiki/Multilingual_names) and [wof](https://github.com/whosonfirst/whosonfirst-names) are solely based off language codes (but maybe I missed something).

For osm features, it tries to map to either an iso-639 1, 2, or 3 code. If it doesn't find one, like in your example, it would just drop that language code. For wof, it always assumes it's an iso-639-3 code.

**Comment by zerebubuth** [comment]
I've found a single `name:en_GB` node [on taginfo](http://taginfo.openstreetmap.org/keys/name%3Aen_GB); [Londonderry/Derry](http://www.openstreetmap.org/node/267762522).

**Comment by nvkelso** [comment]
I love places in the water! 

Cool that it also has a `name:en_IE` variant, and that `name` is the GB and IE variants concatenated together. Good example!

@thisisaaronland to clarify the WOF'ism around similar `languagecode_countrycode` & provide sample data (Japanese, Brazilian Portuguese?).

**Comment by zerebubuth** [comment]
To make matters _more_ complicated. I looked at [Jerusalem](http://www.openstreetmap.org/node/29090735) and there are some 3-letter codes on there, e.g: `name:arz`, `name:arc`, `name:ast`. And some extensions that I'm not sure how to parse: `name:bat-smg` and `name:be-tarask`, `name:zh-min-nan`.

**Comment by nvkelso** [comment]
Summarizing the call:
- Add **small whitelist to normalize** transitional / historic / well-known-funk keys like name:`zh-yue` to name:`yue` as a preprocessing step.
  - If the language code + region code still aren't valid after this transform, don't bother exporting this data error as it should be fixed upstream.
- **Add region code support:** Add logic to look for `_aa` region (country) code postfix, strip that out for middle processing, then add it back after the language code it expanded. 
  - **Example:** name:`en_IE` it'd be `en` and `IE`, then expanded to `eng`, and then concatenated finally to be `eng_IE`. 
  - **Question:** Should IE be lowercase? What's the standard around that?
- I'll update here when there is a WOF region code example and script example. 

New question:
- **Why 3 char codes instead of 2 char codes?** Looks like Android, iOS, and OS X all use 2 char codes.

Comments:
- Looks like some platforms prefix the region code with an `r` (I'm looking at you, Android). Let's not do that!
- Looks like some platforms use a `-` concatenation symbol, others use `_`. (I'm partial to `_`.)

See also:
- https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html
- http://www.ibabbleon.com/iOS-Language-Codes-ISO-639.html
- https://gist.github.com/jacobbubu/1836273
- https://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources

**Comment by rmarianski** [comment]
> Why 3 char codes instead of 2 char codes? Looks like Android, iOS, and OS X all use 2 char codes.

iso-639-3 is a newer standard than iso-639-1 and that's what wof uses.

**Comment by rmarianski** [comment]
Do we also want to verify that any possible country code suffixes are valid? The standard is [iso 3166](https://en.wikipedia.org/wiki/ISO_3166). And if so, do we want to normalize for 2 or 3 characters here too? According to the wikipedia page, the 2 char codes are more popular, and that's what was in the example element. As far as casing goes, the standard has them uppercase, and so does the example, but not sure if we want to make them lower case for aesthetic reasons.

**Comment by nvkelso** [comment]
Yes, let's sanity check the country codes and I'm fine with UPPER.

**Comment by rmarianski** [comment]
Added support for lookups for common spellings and country suffixes in aaf5dfc.

**Pull request merged**
